---
  - name: "Get {{user}} uid"
    shell: "id -u {{user}}"
    register: uid
    when: uid is not defined

  - name: "Get {{user}} gid"
    shell: "id -g {{user}}"
    register: gid
    when: gid is not defined

  - name: Stop and remove any existing container
    docker_container:
      name: tvheadend
      state: absent

  - name: Create required directories
    file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
    with_items:
      - /opt/tvheadend
      - /opt/tvheadend/data

  - name: Create and start tvheadend container
    docker_container:
      name: tvheadend
      image: "linuxserver/tvheadend:release-4.2"
      published_ports:
        - "127.0.0.1:9981:9981"
        - "9982:9982"
      env:
        PUID: "{{uid.stdout}}"
        PGID: "{{gid.stdout}}"
        VIRTUAL_HOST: "tvheadend.{{domain}}"
        VIRTUAL_PORT: 9981
        LETSENCRYPT_HOST: "tvheadend.{{domain}}"
        LETSENCRYPT_EMAIL: "{{email}}"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/opt/tvheadend:/config"
      networks:
        - name: cloudbox
          ipv4_address: 172.18.0.20
          aliases:
            - tvheadend
      restart_policy: always
      state: started

  - name: Check sstv-pipe-play.py exists
    stat:
      path: /opt/tvheadend/sstv-pipe-play.py
    register: sstv_pipe_play

  - name: Import sstv-pipe-play.py
    copy: "src=sstv-pipe-play.py dest=/opt/tvheadend/sstv-pipe-play.py force=yes owner={{user}} group={{user}} mode=0775"
    when: sstv_pipe_play.stat.exists == False

  - name: Import sstv-pipe-playlist.py
    copy: "src=sstv-pipe-playlist.py dest=/opt/tvheadend/sstv-pipe-playlist.py force=yes owner={{user}} group={{user}} mode=0775"
    